version: '3.9'

services:
 
  bot-rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: discord-bot-rabbitmq
    hostname: rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    extra_hosts:
      - "host.docker.internal:172.17.0.1"




volumes:
  mongodb_data:
    driver: local